from pathlib import Path

import pytest

import acts
import acts.examples
from acts import UnitConstants as u

from helpers import arrowEnabled, dd4hepEnabled

pytestmark = [
    pytest.mark.skipif(not arrowEnabled, reason="Arrow/Parquet bindings not built"),
    pytest.mark.skipif(not dd4hepEnabled, reason="DD4hep not set up"),
]

_srcdir = Path(__file__).resolve().parent.parent.parent.parent

# Number of events generated by the FATRAS fixture and processed by the test.
_N_EVENTS = 3


@pytest.fixture(scope="session")
def colliderml_fatras_sample(tmp_path_factory):
    """Generate a small ColliderML-compatible parquet dataset using FATRAS + ODD.

    Runs a minimal sequencer: ParametricParticleGenerator → FATRAS → Digitization
    → ArrowParticleOutputConverter + ArrowSimHitOutputConverter → ParquetWriter.

    Returns (base_dir, sample_name).
    """
    from acts.arrow import particleSchema, simHitSchema
    from acts.examples.arrow import (
        ArrowParticleOutputConverter,
        ArrowSimHitOutputConverter,
        ParquetWriter,
    )
    from acts.examples.json import readDigiConfigFromJson
    from acts.examples.odd import getOpenDataDetector

    sample = "fatras_test"
    tmp = tmp_path_factory.mktemp("colliderml_fatras")

    particles_dir = tmp / f"{sample}_particles" / "data" / f"{sample}_particles"
    hits_dir = tmp / f"{sample}_tracker_hits" / "data" / f"{sample}_tracker_hits"
    particles_dir.mkdir(parents=True)
    hits_dir.mkdir(parents=True)

    rng = acts.examples.RandomNumbers(seed=42)
    field = acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))

    with getOpenDataDetector() as detector:
        tgeo = detector.trackingGeometry()

        s = acts.examples.Sequencer(
            events=_N_EVENTS,
            numThreads=1,
            logLevel=acts.logging.WARNING,
            outputDir=str(tmp),
            failOnUnmaskedFpe=False,
        )

        # --- Particle gun: 10 muons per event, pT=2 GeV, full eta/phi ---
        evGen = acts.examples.EventGenerator(
            level=acts.logging.WARNING,
            generators=[
                acts.examples.EventGenerator.Generator(
                    multiplicity=acts.examples.FixedMultiplicityGenerator(n=1),
                    vertex=acts.examples.GaussianVertexGenerator(
                        stddev=acts.Vector4(0, 0, 0, 0),
                        mean=acts.Vector4(0, 0, 0, 0),
                    ),
                    particles=acts.examples.ParametricParticleGenerator(
                        p=(2 * u.GeV, 2 * u.GeV),
                        eta=(-2, 2),
                        phi=(0, 360 * u.degree),
                        pdg=acts.PdgParticle.eMuon,
                        randomizeCharge=True,
                        numParticles=10,
                    ),
                )
            ],
            outputEvent="gun_event",
            randomNumbers=rng,
        )
        s.addReader(evGen)

        hepmc3Conv = acts.examples.hepmc3.HepMC3InputConverter(
            level=acts.logging.WARNING,
            inputEvent=evGen.config.outputEvent,
            outputParticles="particles_gen",
            outputVertices="vertices_gen",
        )
        s.addAlgorithm(hepmc3Conv)

        # --- FATRAS simulation ---
        fatrasAlg = acts.examples.FatrasSimulation(
            level=acts.logging.WARNING,
            inputParticles="particles_gen",
            outputParticles="particles_sim",
            outputSimHits="simhits",
            randomNumbers=rng,
            trackingGeometry=tgeo,
            magneticField=field,
            generateHitsOnSensitive=True,
            emScattering=False,
            emEnergyLossIonisation=False,
            emEnergyLossRadiation=False,
            emPhotonConversion=False,
        )
        s.addAlgorithm(fatrasAlg)

        # --- Digitization (needed for valid x/y/z cluster positions) ---
        digiCfg = acts.examples.DigitizationAlgorithm.Config(
            digitizationConfigs=readDigiConfigFromJson(
                str(_srcdir / "Examples/Configs/odd-digi-smearing-config-notime.json")
            ),
            surfaceByIdentifier=tgeo.geoIdSurfaceMap(),
            randomNumbers=rng,
            inputSimHits="simhits",
        )
        s.addAlgorithm(
            acts.examples.DigitizationAlgorithm(digiCfg, acts.logging.WARNING)
        )

        # --- Arrow output converters ---
        s.addAlgorithm(
            ArrowParticleOutputConverter(
                level=acts.logging.WARNING,
                inputParticles="particles_sim",
                outputTable="cml_particles_arrow",
            )
        )
        s.addAlgorithm(
            ArrowSimHitOutputConverter(
                level=acts.logging.WARNING,
                inputSimHits="simhits",
                inputParticles="particles_sim",
                inputClusters="clusters",
                inputSimHitMeasurementsMap="simhit_measurements_map",
                outputTable="cml_hits_arrow",
            )
        )

        # --- ParquetWriter: absolute paths so files land in the nested layout ---
        s.addWriter(
            ParquetWriter(
                level=acts.logging.WARNING,
                outputDir=str(tmp),
                collections={
                    "cml_particles_arrow": str(particles_dir),
                    "cml_hits_arrow": str(hits_dir),
                },
                expectedSchemas={
                    "cml_particles_arrow": particleSchema(),
                    "cml_hits_arrow": simHitSchema(),
                },
                eventsPerShard=_N_EVENTS,
            )
        )

        s.run()

    return tmp, sample


@pytest.mark.parametrize("reco_geo", ["gen1", "gen3"])
def test_colliderml_truth_tracking(
    tmp_path, assert_root_hash, colliderml_fatras_sample, reco_geo
):
    """Read FATRAS-generated ColliderML-format data and run truth-seeded KF tracking.

    Parametrized on the reconstruction geometry:
      gen1 — same Gen1 ODD used for simulation; no geo-id map needed.
      gen3 — Gen3 ODD; geo-id map and digi config generated on the fly.

    Verifies that the ColliderML reader pipeline (ParquetReader +
    ColliderMLRelease1InputConverter + TruthEstimated seeding + KF) runs without
    error and produces ROOT output files with the expected content hashes.
    """
    import sys

    sys.path.insert(0, str(_srcdir / "Examples/Scripts/Python"))
    from acts.examples.odd import getOpenDataDetector
    from colliderml_truth_tracking import runColliderMLTruthTracking
    from generate_geoid_map import generate_geoid_map

    inputDir, sample = colliderml_fatras_sample
    field = acts.ConstantBField(acts.Vector3(0, 0, 2 * u.T))

    if reco_geo == "gen3":
        # Build both geometries to generate the mapping on the fly
        detector_gen1 = getOpenDataDetector()
        geo_gen1 = detector_gen1.trackingGeometry()

        detector_gen3 = getOpenDataDetector(gen3=True)
        trackingGeometry = detector_gen3.trackingGeometry()
        decorators = detector_gen3.contextDecorators()

        geoid_map_path = tmp_path / "geoid_map.csv"
        generate_geoid_map(
            geo_gen1,
            trackingGeometry,
            output_path=geoid_map_path,
            prefix_a="gen1",
            prefix_b="gen3",
        )

        ctx = None
    else:
        odd_dir = acts.examples.odd.getOpenDataDetectorDirectory()
        matDeco = acts.IMaterialDecorator.fromFile(
            odd_dir / "data/odd-material-maps.root", level=acts.logging.WARNING
        )
        detector = getOpenDataDetector(matDeco)
        trackingGeometry = detector.trackingGeometry()
        decorators = detector.contextDecorators()
        ctx = detector

    def _run():
        s, _perf_proto, _perf_kf = runColliderMLTruthTracking(
            trackingGeometry=trackingGeometry,
            field=field,
            outputDir=tmp_path,
            inputDir=inputDir,
            geoIdMapPath=geoid_map_path if reco_geo == "gen3" else None,
            decorators=decorators,
            events=_N_EVENTS,
            numThreads=1,
            sample=sample,
        )
        s.run()

    if ctx is not None:
        with ctx:
            _run()
    else:
        _run()

    root_files = [
        "trackstates_kf.root",
        "tracksummary_kf.root",
        "performance_kf.root",
    ]

    for fn in root_files:
        fp = tmp_path / fn
        assert fp.exists(), f"{fn} was not produced"
        assert fp.stat().st_size > 1024, f"{fn} is suspiciously small"
        assert_root_hash(fn, fp)
