version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "pre-commit"
    directory: "/"
    target-branch: "pre-commit-bot"
    schedule:
      interval: "weekly"
