policy:
  approval:
  - One of the reviewers has approved

approval_rules:
- name: One of the reviewers has approved
  requires:
    count: 1
    teams:
    - "acts-project/reviewers"
  options:
    allow_author: false # just for completeness
    allow_contributor: true # Update button 'contributions' should be ignored
    invalidate_on_push: true
    ignore_update_merges: true
