#!/bin/sh

if [ -z "$CMTCONFIG" ] ; then
  echo "error: CMTCONFIG not defined"
  exit 1
fi

run_cmd=$(dirname $0)/build.$CMTCONFIG/run
if [ -e "$run_cmd" ] ; then
  exec $run_cmd "$@"
else
  echo "error: cannot find build.$CMTCONFIG/run, did you build?"
  exit 1
fi
