def write_out_file_to_fp(code, output):
    output.write("""// This file is part of the ACTS project.
        //
        // Copyright (C) 2016 CERN for the benefit of the ACTS project
        //
        // This Source Code Form is subject to the terms of the Mozilla Public
        // License, v. 2.0. If a copy of the MPL was not distributed with this
        // file, You can obtain one at https://mozilla.org/MPL/2.0/.

        // Note: This file is generated by generate_sympy_cov.py
        //       Do not modify it manually.

        #pragma once

        #include "detray/definitions/algebra.hpp"
        #include "detray/definitions/detail/qualifiers.hpp"
        #include "detray/algebra/type_traits.hpp"

        namespace detray::detail {
        """)
    output.write(code)
    output.write("}")


def write_out_file(code, file_name=None):
    if file_name is None:
        write_out_file_to_fp(code, sys.stdout)
    else:
        with open(file_name, "w") as f:
            write_out_file_to_fp(code, f)
