def write_out_file_to_fp(code, output):
    output.write("""/* Detray library, part of the ACTS project (R&D line)
         *
         * (c) 2025 CERN for the benefit of the ACTS project
         *
         * Mozilla Public License Version 2.0
         *
         * Note: This file is automatically generated.
         *       Do not modify it manually.
         */

        #pragma once

        #include "detray/definitions/algebra.hpp"
        #include "detray/definitions/detail/qualifiers.hpp"
        #include "detray/algebra/type_traits.hpp"

        namespace detray::detail {
        """)
    output.write(code)
    output.write("}")


def write_out_file(code, file_name=None):
    if file_name is None:
        write_out_file_to_fp(code, sys.stdout)
    else:
        with open(file_name, "w") as f:
            write_out_file_to_fp(code, f)
