// This file is part of the ACTS project.
//
// Copyright (C) 2016 CERN for the benefit of the ACTS project
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

/* Detray library, part of the ACTS project (R&D line)
 *
 * (c) 2025 CERN for the benefit of the ACTS project
 *
 * Mozilla Public License Version 2.0
 *
 * Note: This file is automatically generated.
 *       Do not modify it manually.
 */

#pragma once

#include "detray/algebra/type_traits.hpp"
#include "detray/definitions/algebra.hpp"
#include "detray/definitions/detail/qualifiers.hpp"

namespace detray::detail {
template <typename C_t, typename J_full_t, typename new_C_t>
DETRAY_HOST_DEVICE void inline transport_covariance_to_bound_impl(
    const C_t& C, const J_full_t& J_full, new_C_t& new_C)
  requires((detray::concepts::square_matrix<C_t> &&
            detray::traits::max_rank<C_t> == 6) &&
           (detray::concepts::square_matrix<J_full_t> &&
            detray::traits::max_rank<J_full_t> == 6) &&
           (detray::concepts::square_matrix<new_C_t> &&
            detray::traits::max_rank<new_C_t> == 6))
{
  assert((getter::element<0, 5>(J_full) == 0.f));
  assert((getter::element<1, 5>(J_full) == 0.f));
  assert((getter::element<2, 5>(J_full) == 0.f));
  assert((getter::element<3, 5>(J_full) == 0.f));
  assert((getter::element<4, 0>(J_full) == 0.f));
  assert((getter::element<4, 1>(J_full) == 0.f));
  assert((getter::element<4, 2>(J_full) == 0.f));
  assert((getter::element<4, 3>(J_full) == 0.f));
  assert((getter::element<4, 4>(J_full) == 1.f));
  assert((getter::element<4, 5>(J_full) == 0.f));
  assert((getter::element<5, 5>(J_full) == 1.f));
  const auto x4 = getter::element<4, 4>(C) * getter::element<0, 4>(J_full);
  const auto x10 = getter::element<4, 4>(C) * getter::element<1, 4>(J_full);
  const auto x16 = getter::element<4, 4>(C) * getter::element<2, 4>(J_full);
  const auto x22 = getter::element<4, 4>(C) * getter::element<3, 4>(J_full);
  const auto x24 = getter::element<4, 4>(C) * getter::element<5, 4>(J_full);
  const auto x0 = getter::element<0, 0>(C) * getter::element<0, 0>(J_full) +
                  getter::element<1, 0>(C) * getter::element<0, 1>(J_full) +
                  getter::element<2, 0>(C) * getter::element<0, 2>(J_full) +
                  getter::element<3, 0>(C) * getter::element<0, 3>(J_full) +
                  getter::element<4, 0>(C) * getter::element<0, 4>(J_full);
  const auto x1 = getter::element<0, 1>(C) * getter::element<0, 0>(J_full) +
                  getter::element<1, 1>(C) * getter::element<0, 1>(J_full) +
                  getter::element<2, 1>(C) * getter::element<0, 2>(J_full) +
                  getter::element<3, 1>(C) * getter::element<0, 3>(J_full) +
                  getter::element<4, 1>(C) * getter::element<0, 4>(J_full);
  const auto x2 = getter::element<0, 2>(C) * getter::element<0, 0>(J_full) +
                  getter::element<1, 2>(C) * getter::element<0, 1>(J_full) +
                  getter::element<2, 2>(C) * getter::element<0, 2>(J_full) +
                  getter::element<3, 2>(C) * getter::element<0, 3>(J_full) +
                  getter::element<4, 2>(C) * getter::element<0, 4>(J_full);
  const auto x3 = getter::element<0, 3>(C) * getter::element<0, 0>(J_full) +
                  getter::element<1, 3>(C) * getter::element<0, 1>(J_full) +
                  getter::element<2, 3>(C) * getter::element<0, 2>(J_full) +
                  getter::element<3, 3>(C) * getter::element<0, 3>(J_full) +
                  getter::element<4, 3>(C) * getter::element<0, 4>(J_full);
  const auto x6 = getter::element<0, 0>(C) * getter::element<1, 0>(J_full) +
                  getter::element<1, 0>(C) * getter::element<1, 1>(J_full) +
                  getter::element<2, 0>(C) * getter::element<1, 2>(J_full) +
                  getter::element<3, 0>(C) * getter::element<1, 3>(J_full) +
                  getter::element<4, 0>(C) * getter::element<1, 4>(J_full);
  const auto x7 = getter::element<0, 1>(C) * getter::element<1, 0>(J_full) +
                  getter::element<1, 1>(C) * getter::element<1, 1>(J_full) +
                  getter::element<2, 1>(C) * getter::element<1, 2>(J_full) +
                  getter::element<3, 1>(C) * getter::element<1, 3>(J_full) +
                  getter::element<4, 1>(C) * getter::element<1, 4>(J_full);
  const auto x8 = getter::element<0, 2>(C) * getter::element<1, 0>(J_full) +
                  getter::element<1, 2>(C) * getter::element<1, 1>(J_full) +
                  getter::element<2, 2>(C) * getter::element<1, 2>(J_full) +
                  getter::element<3, 2>(C) * getter::element<1, 3>(J_full) +
                  getter::element<4, 2>(C) * getter::element<1, 4>(J_full);
  const auto x9 = getter::element<0, 3>(C) * getter::element<1, 0>(J_full) +
                  getter::element<1, 3>(C) * getter::element<1, 1>(J_full) +
                  getter::element<2, 3>(C) * getter::element<1, 2>(J_full) +
                  getter::element<3, 3>(C) * getter::element<1, 3>(J_full) +
                  getter::element<4, 3>(C) * getter::element<1, 4>(J_full);
  const auto x12 = getter::element<0, 0>(C) * getter::element<2, 0>(J_full) +
                   getter::element<1, 0>(C) * getter::element<2, 1>(J_full) +
                   getter::element<2, 0>(C) * getter::element<2, 2>(J_full) +
                   getter::element<3, 0>(C) * getter::element<2, 3>(J_full) +
                   getter::element<4, 0>(C) * getter::element<2, 4>(J_full);
  const auto x13 = getter::element<0, 1>(C) * getter::element<2, 0>(J_full) +
                   getter::element<1, 1>(C) * getter::element<2, 1>(J_full) +
                   getter::element<2, 1>(C) * getter::element<2, 2>(J_full) +
                   getter::element<3, 1>(C) * getter::element<2, 3>(J_full) +
                   getter::element<4, 1>(C) * getter::element<2, 4>(J_full);
  const auto x14 = getter::element<0, 2>(C) * getter::element<2, 0>(J_full) +
                   getter::element<1, 2>(C) * getter::element<2, 1>(J_full) +
                   getter::element<2, 2>(C) * getter::element<2, 2>(J_full) +
                   getter::element<3, 2>(C) * getter::element<2, 3>(J_full) +
                   getter::element<4, 2>(C) * getter::element<2, 4>(J_full);
  const auto x15 = getter::element<0, 3>(C) * getter::element<2, 0>(J_full) +
                   getter::element<1, 3>(C) * getter::element<2, 1>(J_full) +
                   getter::element<2, 3>(C) * getter::element<2, 2>(J_full) +
                   getter::element<3, 3>(C) * getter::element<2, 3>(J_full) +
                   getter::element<4, 3>(C) * getter::element<2, 4>(J_full);
  const auto x18 = getter::element<0, 0>(C) * getter::element<3, 0>(J_full) +
                   getter::element<1, 0>(C) * getter::element<3, 1>(J_full) +
                   getter::element<2, 0>(C) * getter::element<3, 2>(J_full) +
                   getter::element<3, 0>(C) * getter::element<3, 3>(J_full) +
                   getter::element<4, 0>(C) * getter::element<3, 4>(J_full);
  const auto x19 = getter::element<0, 1>(C) * getter::element<3, 0>(J_full) +
                   getter::element<1, 1>(C) * getter::element<3, 1>(J_full) +
                   getter::element<2, 1>(C) * getter::element<3, 2>(J_full) +
                   getter::element<3, 1>(C) * getter::element<3, 3>(J_full) +
                   getter::element<4, 1>(C) * getter::element<3, 4>(J_full);
  const auto x20 = getter::element<0, 2>(C) * getter::element<3, 0>(J_full) +
                   getter::element<1, 2>(C) * getter::element<3, 1>(J_full) +
                   getter::element<2, 2>(C) * getter::element<3, 2>(J_full) +
                   getter::element<3, 2>(C) * getter::element<3, 3>(J_full) +
                   getter::element<4, 2>(C) * getter::element<3, 4>(J_full);
  const auto x21 = getter::element<0, 3>(C) * getter::element<3, 0>(J_full) +
                   getter::element<1, 3>(C) * getter::element<3, 1>(J_full) +
                   getter::element<2, 3>(C) * getter::element<3, 2>(J_full) +
                   getter::element<3, 3>(C) * getter::element<3, 3>(J_full) +
                   getter::element<4, 3>(C) * getter::element<3, 4>(J_full);
  const auto x25 = getter::element<0, 0>(C) * getter::element<5, 0>(J_full) +
                   getter::element<1, 0>(C) * getter::element<5, 1>(J_full) +
                   getter::element<2, 0>(C) * getter::element<5, 2>(J_full) +
                   getter::element<3, 0>(C) * getter::element<5, 3>(J_full) +
                   getter::element<4, 0>(C) * getter::element<5, 4>(J_full) +
                   getter::element<5, 0>(C);
  const auto x26 = getter::element<0, 1>(C) * getter::element<5, 0>(J_full) +
                   getter::element<1, 1>(C) * getter::element<5, 1>(J_full) +
                   getter::element<2, 1>(C) * getter::element<5, 2>(J_full) +
                   getter::element<3, 1>(C) * getter::element<5, 3>(J_full) +
                   getter::element<4, 1>(C) * getter::element<5, 4>(J_full) +
                   getter::element<5, 1>(C);
  const auto x27 = getter::element<0, 2>(C) * getter::element<5, 0>(J_full) +
                   getter::element<1, 2>(C) * getter::element<5, 1>(J_full) +
                   getter::element<2, 2>(C) * getter::element<5, 2>(J_full) +
                   getter::element<3, 2>(C) * getter::element<5, 3>(J_full) +
                   getter::element<4, 2>(C) * getter::element<5, 4>(J_full) +
                   getter::element<5, 2>(C);
  const auto x28 = getter::element<0, 3>(C) * getter::element<5, 0>(J_full) +
                   getter::element<1, 3>(C) * getter::element<5, 1>(J_full) +
                   getter::element<2, 3>(C) * getter::element<5, 2>(J_full) +
                   getter::element<3, 3>(C) * getter::element<5, 3>(J_full) +
                   getter::element<4, 3>(C) * getter::element<5, 4>(J_full) +
                   getter::element<5, 3>(C);
  const auto x5 = x4 +
                  getter::element<0, 4>(C) * getter::element<0, 0>(J_full) +
                  getter::element<1, 4>(C) * getter::element<0, 1>(J_full) +
                  getter::element<2, 4>(C) * getter::element<0, 2>(J_full) +
                  getter::element<3, 4>(C) * getter::element<0, 3>(J_full);
  const auto x11 = x10 +
                   getter::element<0, 4>(C) * getter::element<1, 0>(J_full) +
                   getter::element<1, 4>(C) * getter::element<1, 1>(J_full) +
                   getter::element<2, 4>(C) * getter::element<1, 2>(J_full) +
                   getter::element<3, 4>(C) * getter::element<1, 3>(J_full);
  const auto x17 = x16 +
                   getter::element<0, 4>(C) * getter::element<2, 0>(J_full) +
                   getter::element<1, 4>(C) * getter::element<2, 1>(J_full) +
                   getter::element<2, 4>(C) * getter::element<2, 2>(J_full) +
                   getter::element<3, 4>(C) * getter::element<2, 3>(J_full);
  const auto x23 = x22 +
                   getter::element<0, 4>(C) * getter::element<3, 0>(J_full) +
                   getter::element<1, 4>(C) * getter::element<3, 1>(J_full) +
                   getter::element<2, 4>(C) * getter::element<3, 2>(J_full) +
                   getter::element<3, 4>(C) * getter::element<3, 3>(J_full);
  const auto x29 = x24 +
                   getter::element<0, 4>(C) * getter::element<5, 0>(J_full) +
                   getter::element<1, 4>(C) * getter::element<5, 1>(J_full) +
                   getter::element<2, 4>(C) * getter::element<5, 2>(J_full) +
                   getter::element<3, 4>(C) * getter::element<5, 3>(J_full) +
                   getter::element<5, 4>(C);
  getter::element<0, 0>(new_C) =
      x0 * getter::element<0, 0>(J_full) + x1 * getter::element<0, 1>(J_full) +
      x2 * getter::element<0, 2>(J_full) + x3 * getter::element<0, 3>(J_full) +
      x5 * getter::element<0, 4>(J_full);
  getter::element<1, 0>(new_C) =
      x11 * getter::element<0, 4>(J_full) + x6 * getter::element<0, 0>(J_full) +
      x7 * getter::element<0, 1>(J_full) + x8 * getter::element<0, 2>(J_full) +
      x9 * getter::element<0, 3>(J_full);
  getter::element<2, 0>(new_C) = x12 * getter::element<0, 0>(J_full) +
                                 x13 * getter::element<0, 1>(J_full) +
                                 x14 * getter::element<0, 2>(J_full) +
                                 x15 * getter::element<0, 3>(J_full) +
                                 x17 * getter::element<0, 4>(J_full);
  getter::element<3, 0>(new_C) = x18 * getter::element<0, 0>(J_full) +
                                 x19 * getter::element<0, 1>(J_full) +
                                 x20 * getter::element<0, 2>(J_full) +
                                 x21 * getter::element<0, 3>(J_full) +
                                 x23 * getter::element<0, 4>(J_full);
  getter::element<4, 0>(new_C) =
      x4 + getter::element<4, 0>(C) * getter::element<0, 0>(J_full) +
      getter::element<4, 1>(C) * getter::element<0, 1>(J_full) +
      getter::element<4, 2>(C) * getter::element<0, 2>(J_full) +
      getter::element<4, 3>(C) * getter::element<0, 3>(J_full);
  getter::element<5, 0>(new_C) = x25 * getter::element<0, 0>(J_full) +
                                 x26 * getter::element<0, 1>(J_full) +
                                 x27 * getter::element<0, 2>(J_full) +
                                 x28 * getter::element<0, 3>(J_full) +
                                 x29 * getter::element<0, 4>(J_full);
  getter::element<0, 1>(new_C) =
      x0 * getter::element<1, 0>(J_full) + x1 * getter::element<1, 1>(J_full) +
      x2 * getter::element<1, 2>(J_full) + x3 * getter::element<1, 3>(J_full) +
      x5 * getter::element<1, 4>(J_full);
  getter::element<1, 1>(new_C) =
      x11 * getter::element<1, 4>(J_full) + x6 * getter::element<1, 0>(J_full) +
      x7 * getter::element<1, 1>(J_full) + x8 * getter::element<1, 2>(J_full) +
      x9 * getter::element<1, 3>(J_full);
  getter::element<2, 1>(new_C) = x12 * getter::element<1, 0>(J_full) +
                                 x13 * getter::element<1, 1>(J_full) +
                                 x14 * getter::element<1, 2>(J_full) +
                                 x15 * getter::element<1, 3>(J_full) +
                                 x17 * getter::element<1, 4>(J_full);
  getter::element<3, 1>(new_C) = x18 * getter::element<1, 0>(J_full) +
                                 x19 * getter::element<1, 1>(J_full) +
                                 x20 * getter::element<1, 2>(J_full) +
                                 x21 * getter::element<1, 3>(J_full) +
                                 x23 * getter::element<1, 4>(J_full);
  getter::element<4, 1>(new_C) =
      x10 + getter::element<4, 0>(C) * getter::element<1, 0>(J_full) +
      getter::element<4, 1>(C) * getter::element<1, 1>(J_full) +
      getter::element<4, 2>(C) * getter::element<1, 2>(J_full) +
      getter::element<4, 3>(C) * getter::element<1, 3>(J_full);
  getter::element<5, 1>(new_C) = x25 * getter::element<1, 0>(J_full) +
                                 x26 * getter::element<1, 1>(J_full) +
                                 x27 * getter::element<1, 2>(J_full) +
                                 x28 * getter::element<1, 3>(J_full) +
                                 x29 * getter::element<1, 4>(J_full);
  getter::element<0, 2>(new_C) =
      x0 * getter::element<2, 0>(J_full) + x1 * getter::element<2, 1>(J_full) +
      x2 * getter::element<2, 2>(J_full) + x3 * getter::element<2, 3>(J_full) +
      x5 * getter::element<2, 4>(J_full);
  getter::element<1, 2>(new_C) =
      x11 * getter::element<2, 4>(J_full) + x6 * getter::element<2, 0>(J_full) +
      x7 * getter::element<2, 1>(J_full) + x8 * getter::element<2, 2>(J_full) +
      x9 * getter::element<2, 3>(J_full);
  getter::element<2, 2>(new_C) = x12 * getter::element<2, 0>(J_full) +
                                 x13 * getter::element<2, 1>(J_full) +
                                 x14 * getter::element<2, 2>(J_full) +
                                 x15 * getter::element<2, 3>(J_full) +
                                 x17 * getter::element<2, 4>(J_full);
  getter::element<3, 2>(new_C) = x18 * getter::element<2, 0>(J_full) +
                                 x19 * getter::element<2, 1>(J_full) +
                                 x20 * getter::element<2, 2>(J_full) +
                                 x21 * getter::element<2, 3>(J_full) +
                                 x23 * getter::element<2, 4>(J_full);
  getter::element<4, 2>(new_C) =
      x16 + getter::element<4, 0>(C) * getter::element<2, 0>(J_full) +
      getter::element<4, 1>(C) * getter::element<2, 1>(J_full) +
      getter::element<4, 2>(C) * getter::element<2, 2>(J_full) +
      getter::element<4, 3>(C) * getter::element<2, 3>(J_full);
  getter::element<5, 2>(new_C) = x25 * getter::element<2, 0>(J_full) +
                                 x26 * getter::element<2, 1>(J_full) +
                                 x27 * getter::element<2, 2>(J_full) +
                                 x28 * getter::element<2, 3>(J_full) +
                                 x29 * getter::element<2, 4>(J_full);
  getter::element<0, 3>(new_C) =
      x0 * getter::element<3, 0>(J_full) + x1 * getter::element<3, 1>(J_full) +
      x2 * getter::element<3, 2>(J_full) + x3 * getter::element<3, 3>(J_full) +
      x5 * getter::element<3, 4>(J_full);
  getter::element<1, 3>(new_C) =
      x11 * getter::element<3, 4>(J_full) + x6 * getter::element<3, 0>(J_full) +
      x7 * getter::element<3, 1>(J_full) + x8 * getter::element<3, 2>(J_full) +
      x9 * getter::element<3, 3>(J_full);
  getter::element<2, 3>(new_C) = x12 * getter::element<3, 0>(J_full) +
                                 x13 * getter::element<3, 1>(J_full) +
                                 x14 * getter::element<3, 2>(J_full) +
                                 x15 * getter::element<3, 3>(J_full) +
                                 x17 * getter::element<3, 4>(J_full);
  getter::element<3, 3>(new_C) = x18 * getter::element<3, 0>(J_full) +
                                 x19 * getter::element<3, 1>(J_full) +
                                 x20 * getter::element<3, 2>(J_full) +
                                 x21 * getter::element<3, 3>(J_full) +
                                 x23 * getter::element<3, 4>(J_full);
  getter::element<4, 3>(new_C) =
      x22 + getter::element<4, 0>(C) * getter::element<3, 0>(J_full) +
      getter::element<4, 1>(C) * getter::element<3, 1>(J_full) +
      getter::element<4, 2>(C) * getter::element<3, 2>(J_full) +
      getter::element<4, 3>(C) * getter::element<3, 3>(J_full);
  getter::element<5, 3>(new_C) = x25 * getter::element<3, 0>(J_full) +
                                 x26 * getter::element<3, 1>(J_full) +
                                 x27 * getter::element<3, 2>(J_full) +
                                 x28 * getter::element<3, 3>(J_full) +
                                 x29 * getter::element<3, 4>(J_full);
  getter::element<0, 4>(new_C) = x5;
  getter::element<1, 4>(new_C) = x11;
  getter::element<2, 4>(new_C) = x17;
  getter::element<3, 4>(new_C) = x23;
  getter::element<4, 4>(new_C) = getter::element<4, 4>(C);
  getter::element<5, 4>(new_C) = x29;
  getter::element<0, 5>(new_C) =
      x0 * getter::element<5, 0>(J_full) + x1 * getter::element<5, 1>(J_full) +
      x2 * getter::element<5, 2>(J_full) + x3 * getter::element<5, 3>(J_full) +
      x5 * getter::element<5, 4>(J_full) +
      getter::element<0, 5>(C) * getter::element<0, 0>(J_full) +
      getter::element<1, 5>(C) * getter::element<0, 1>(J_full) +
      getter::element<2, 5>(C) * getter::element<0, 2>(J_full) +
      getter::element<3, 5>(C) * getter::element<0, 3>(J_full) +
      getter::element<4, 5>(C) * getter::element<0, 4>(J_full);
  getter::element<1, 5>(new_C) =
      x11 * getter::element<5, 4>(J_full) + x6 * getter::element<5, 0>(J_full) +
      x7 * getter::element<5, 1>(J_full) + x8 * getter::element<5, 2>(J_full) +
      x9 * getter::element<5, 3>(J_full) +
      getter::element<0, 5>(C) * getter::element<1, 0>(J_full) +
      getter::element<1, 5>(C) * getter::element<1, 1>(J_full) +
      getter::element<2, 5>(C) * getter::element<1, 2>(J_full) +
      getter::element<3, 5>(C) * getter::element<1, 3>(J_full) +
      getter::element<4, 5>(C) * getter::element<1, 4>(J_full);
  getter::element<2, 5>(new_C) =
      x12 * getter::element<5, 0>(J_full) +
      x13 * getter::element<5, 1>(J_full) +
      x14 * getter::element<5, 2>(J_full) +
      x15 * getter::element<5, 3>(J_full) +
      x17 * getter::element<5, 4>(J_full) +
      getter::element<0, 5>(C) * getter::element<2, 0>(J_full) +
      getter::element<1, 5>(C) * getter::element<2, 1>(J_full) +
      getter::element<2, 5>(C) * getter::element<2, 2>(J_full) +
      getter::element<3, 5>(C) * getter::element<2, 3>(J_full) +
      getter::element<4, 5>(C) * getter::element<2, 4>(J_full);
  getter::element<3, 5>(new_C) =
      x18 * getter::element<5, 0>(J_full) +
      x19 * getter::element<5, 1>(J_full) +
      x20 * getter::element<5, 2>(J_full) +
      x21 * getter::element<5, 3>(J_full) +
      x23 * getter::element<5, 4>(J_full) +
      getter::element<0, 5>(C) * getter::element<3, 0>(J_full) +
      getter::element<1, 5>(C) * getter::element<3, 1>(J_full) +
      getter::element<2, 5>(C) * getter::element<3, 2>(J_full) +
      getter::element<3, 5>(C) * getter::element<3, 3>(J_full) +
      getter::element<4, 5>(C) * getter::element<3, 4>(J_full);
  getter::element<4, 5>(new_C) =
      x24 + getter::element<4, 0>(C) * getter::element<5, 0>(J_full) +
      getter::element<4, 1>(C) * getter::element<5, 1>(J_full) +
      getter::element<4, 2>(C) * getter::element<5, 2>(J_full) +
      getter::element<4, 3>(C) * getter::element<5, 3>(J_full) +
      getter::element<4, 5>(C);
  getter::element<5, 5>(new_C) =
      x25 * getter::element<5, 0>(J_full) +
      x26 * getter::element<5, 1>(J_full) +
      x27 * getter::element<5, 2>(J_full) +
      x28 * getter::element<5, 3>(J_full) +
      x29 * getter::element<5, 4>(J_full) +
      getter::element<0, 5>(C) * getter::element<5, 0>(J_full) +
      getter::element<1, 5>(C) * getter::element<5, 1>(J_full) +
      getter::element<2, 5>(C) * getter::element<5, 2>(J_full) +
      getter::element<3, 5>(C) * getter::element<5, 3>(J_full) +
      getter::element<4, 5>(C) * getter::element<5, 4>(J_full) +
      getter::element<5, 5>(C);
}
}  // namespace detray::detail
