// This file is part of the Acts project.
//
// Copyright (C) 2020-2021 CERN for the benefit of the Acts project
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#pragma once

#include "ActsFatras/EventData/Hit.hpp"
#include "ActsFatras/EventData/Particle.hpp"

#include <iosfwd>
#include <limits>
#include <vector>

namespace ActsFatras {

/// Particle simulation status.
enum class SimulationParticleStatus {
  /// Particle is alive and can be simulated further.
  eAlive,
  /// Particle has been killed by an interaction.
  eInteracted,
  /// Particle has decayed.
  eDecayed,
};

std::ostream& operator<<(std::ostream& os, SimulationParticleStatus status);

/// Single particle simulation result (and intermediate state).
///
/// This result struct is used by multiple components and is thus defined here,
/// separately from its usage.
struct SimulationResult {
  /// Current/ final particle state.
  Particle particle;
  /// Status flag, e.g. if the particle is alive and can be simulated further
  SimulationParticleStatus particleStatus = SimulationParticleStatus::eAlive;
  /// Additional particles generated by interactions.
  std::vector<Particle> generatedParticles;
  /// Hits created by the particle.
  std::vector<Hit> hits;

  // The following variables are internal simulation state implementation
  // details that must be defined here for technical reasons.

  // Accumulated particle proper time since the start of the simulation.
  //
  // Initialized to NaN so the simulation actor can detect when it is called
  // for the first time, i.e. when the result struct is default-initialized.
  Particle::Scalar properTime =
      std::numeric_limits<Particle::Scalar>::quiet_NaN();
  // Accumulated radiation/interaction length limit before next interaction.
  Particle::Scalar x0Limit = std::numeric_limits<Particle::Scalar>::infinity();
  Particle::Scalar l0Limit = std::numeric_limits<Particle::Scalar>::infinity();
  // Process selection for the next interaction.
  size_t x0Process = SIZE_MAX;
  size_t l0Process = SIZE_MAX;
};

}  // namespace ActsFatras
