// This file is part of the ACTS project.
//
// Copyright (C) 2016 CERN for the benefit of the ACTS project
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

/** Detray library, part of the ACTS project (R&D line)
 *
 * (c) 2022-2024 CERN for the benefit of the ACTS project
 *
 * Mozilla Public License Version 2.0
 */

#pragma once

// Project include(s)
#include "detray/utils/logging.hpp"
#include "detray/utils/type_list.hpp"
#include "detray/version.hpp"  // generated by cmake

// System include(s).
#include <chrono>
#include <iomanip>
#include <iostream>
#include <locale>
#include <sstream>
#include <string>
#include <string_view>

namespace detray::io::detail {

template <typename detector_t>
inline void print_type_warning([[maybe_unused]] const std::string& subject) {
  DETRAY_WARN_HOST("Detector of type \n"
                   << DETRAY_TYPENAME(typename detector_t::metadata)
                   << "does not support " << subject);
}

/// @returns a string that contains the current date and time
/// @see https://en.cppreference.com/w/cpp/chrono/year_month_day.html
inline std::string get_current_date() {
  const std::chrono::time_point now{std::chrono::system_clock::now()};
  const std::chrono::year_month_day ymd{
      std::chrono::floor<std::chrono::days>(now)};

  std::ostringstream stream{};
  stream << ymd;

  return stream.str();
}

/// @returns a string that contains the current project version
inline std::string get_detray_version() {
  return "detray - " + std::string(detray::version);
}

static constexpr std::string_view minimal_io_version = "detray - 0.112.0";

}  // namespace detray::io::detail
