// This file is part of the ACTS project.
//
// Copyright (C) 2016 CERN for the benefit of the ACTS project
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#pragma once

#include "Acts/Definitions/Algebra.hpp"
#include "ActsExamples/Framework/RandomNumbers.hpp"

#include <cstddef>
#include <memory>
#include <numbers>
#include <random>
#include <vector>

namespace ActsExamples {

/// @brief Generator interface for a vertex position
struct PrimaryVertexPositionGenerator {
  /// @brief Virtual destructor required
  virtual ~PrimaryVertexPositionGenerator() = default;
  /// @brief Generate a vertex position
  ///
  /// @param rng Shared random number generator instance
  /// @param eventNumber The current event number
  /// @return Acts::Vector4 The vertex position
  virtual Acts::Vector4 operator()(RandomEngine& rng,
                                   std::size_t eventNumber) const = 0;
};

struct FixedPrimaryVertexPositionGenerator
    : public PrimaryVertexPositionGenerator {
  /// The fixed vertex position and time.
  Acts::Vector4 fixed = Acts::Vector4::Zero();

  Acts::Vector4 operator()(RandomEngine& /*rng*/,
                           std::size_t /*eventNumber*/) const override {
    return fixed;
  }
};

struct GaussianPrimaryVertexPositionGenerator
    : public PrimaryVertexPositionGenerator {
  // standard deviation comes first, since it is more likely to be modified
  /// Vertex position and time standard deviation.
  Acts::Vector4 stddev = {0.0, 0.0, 0.0, 0.0};
  /// Mean vertex position and time.
  Acts::Vector4 mean = {0.0, 0.0, 0.0, 0.0};

  Acts::Vector4 operator()(RandomEngine& rng,
                           std::size_t /*eventNumber*/) const override {
    auto normal = std::normal_distribution<double>(0.0, 1.0);
    Acts::Vector4 rndNormal = {
        normal(rng),
        normal(rng),
        normal(rng),
        normal(rng),
    };
    return mean + rndNormal.cwiseProduct(stddev);
  }
};

//
struct GaussianDisplacedVertexPositionGenerator
    : public PrimaryVertexPositionGenerator {
  double rMean = 0;
  double rStdDev = 1;
  double zMean = 0;
  double zStdDev = 1;
  double tMean = 0;
  double tStdDev = 1;

  Acts::Vector4 operator()(RandomEngine& rng,
                           std::size_t /*eventNumber*/) const override {
    double min_value = -std::numbers::pi;
    double max_value = std::numbers::pi;

    std::uniform_real_distribution uniform(min_value, max_value);

    std::normal_distribution rDist(rMean, rStdDev);
    std::normal_distribution zDist(zMean, zStdDev);
    std::normal_distribution tDist(tMean, tStdDev);

    // Generate random values from normal distributions
    double r = rDist(rng);
    double phi = uniform(rng);  // Random angle in radians
    double z = zDist(rng);
    double t = tDist(rng);

    // Convert cylindrical coordinates to Cartesian coordinates
    double x = r * std::cos(phi);
    double y = r * std::sin(phi);

    return Acts::Vector4(x, y, z, t);
  }
};

struct CartesianVertexPositionGenerator
    : public PrimaryVertexPositionGenerator {
  double xMean = 0;
  double xStdDev = 1;
  double yMean = 0;
  double yStdDev = 1;
  double zMean = 0;
  double zStdDev = 1;
  double tMean = 0;
  double tStdDev = 1;

  Acts::Vector4 operator()(RandomEngine& rng, std::size_t /*eventNumber*/) const override {
    

    std::normal_distribution xDist(xMean, xStdDev);
    std::normal_distribution yDist(yMean, yStdDev);
    std::normal_distribution zDist(zMean, zStdDev);
    std::normal_distribution tDist(tMean, tStdDev);

    // Generate random values from normal distributions
    double x = xDist(rng);
    double y = yDist(rng);  // Random angle in radians
    double z = zDist(rng);
    double t = tDist(rng);
    return Acts::Vector4(x, y, z, t);
  }
};

struct UniformPrimaryVertexPositionGenerator
    : public PrimaryVertexPositionGenerator {
  /// Vertex position and time minimum.
  Acts::Vector4 min = {0.0, 0.0, 0.0, 0.0};
  /// Vertex position and time maximum.
  Acts::Vector4 max = {0.0, 0.0, 0.0, 0.0};

  Acts::Vector4 operator()(RandomEngine& rng,
                           std::size_t /*eventNumber*/) const override {
    auto uniform = std::uniform_real_distribution<double>(0.0, 1.0);
    Acts::Vector4 rndUniform = {
        uniform(rng),
        uniform(rng),
        uniform(rng),
        uniform(rng),
    };
    return min + rndUniform.cwiseProduct(max - min);
  }
};

/// @brief Combines multiple vertex position generators additively.
///
/// The output position is the sum of the positions generated by all
/// constituent generators. This allows composing e.g. a per-event Gaussian
/// smearing with a per-lumi-block beamspot drift.
struct AdditiveVertexPositionGenerator : public PrimaryVertexPositionGenerator {
  std::vector<std::shared_ptr<PrimaryVertexPositionGenerator>> generators;

  Acts::Vector4 operator()(RandomEngine& rng,
                           std::size_t eventNumber) const override {
    Acts::Vector4 result = Acts::Vector4::Zero();
    for (const auto& gen : generators) {
      result += (*gen)(rng, eventNumber);
    }
    return result;
  }
};

/// @brief Generates a vertex position that stays constant within a
/// luminosity block and changes between blocks.
///
/// The block is determined by dividing the event number by the block size.
/// A deterministic pseudo-random number generator seeded by the block number
/// is used to produce a Gaussian-distributed offset, so all events within the
/// same block share the same nominal beamspot position.
struct LumiBlockVertexPositionGenerator
    : public PrimaryVertexPositionGenerator {
  /// Number of events per luminosity block.
  std::size_t blockSize = 1000;
  /// Standard deviation of the beamspot position per block.
  Acts::Vector4 stddev = Acts::Vector4::Zero();
  /// Seed for the derived random number generator.
  RandomSeed seed = 0x517cc1b7;

  Acts::Vector4 operator()(RandomEngine& rng,
                           std::size_t eventNumber) const override {
    std::size_t block = eventNumber / blockSize;
    auto blockRng = rng.combinedWith(block).combinedWith(seed);
    std::normal_distribution dist(0.0, 1.0);
    Acts::Vector4 rnd = {
        dist(blockRng),
        dist(blockRng),
        dist(blockRng),
        dist(blockRng),
    };
    return rnd.cwiseProduct(stddev);
  }
};

/// @brief Wraps another vertex generator and applies a per-lumi-block
/// rotation (beam tilt) to its output.
///
/// For each luminosity block, two tilt angles (around x and y) are drawn
/// from Gaussian distributions seeded deterministically by the block number.
/// The rotation is applied to the spatial components only; time is unchanged.
/// Use this inside an AdditiveVertexPositionGenerator together with a
/// LumiBlockVertexPositionGenerator to get both tilt and positional drift.
struct LumiBlockRotationVertexPositionGenerator
    : public PrimaryVertexPositionGenerator {
  /// The base vertex generator whose output is rotated.
  std::shared_ptr<PrimaryVertexPositionGenerator> base;
  /// Number of events per luminosity block.
  std::size_t blockSize = 1000;
  /// Seed for the derived random number generator.
  RandomSeed seed = 0x9e3779b9;
  /// Standard deviation of the tilt angle around the x-axis [rad].
  double xAngleStddev = 0;
  /// Standard deviation of the tilt angle around the y-axis [rad].
  double yAngleStddev = 0;

  Acts::Vector4 operator()(RandomEngine& rng,
                           std::size_t eventNumber) const override {
    std::size_t block = eventNumber / blockSize;
    // Combine user seed with block number and a salt so the rotation
    // is uncorrelated with the positional shift from
    // LumiBlockVertexPositionGenerator using the same block size.
    auto blockRng = rng.combinedWith(block).combinedWith(seed);
    std::normal_distribution dist(0.0, 1.0);
    const double ax = dist(blockRng) * xAngleStddev;
    const double ay = dist(blockRng) * yAngleStddev;

    // Combined rotation Ry * Rx applied to the spatial part
    Acts::Vector4 pos = (*base)(rng, eventNumber);
    const Acts::RotationMatrix3 rot =
        (Eigen::AngleAxisd(ay, Acts::Vector3::UnitY()) *
         Eigen::AngleAxisd(ax, Acts::Vector3::UnitX()))
            .toRotationMatrix();
    pos.segment<3>(0) = rot * pos.segment<3>(0);

    return pos;
  }
};

}  // namespace ActsExamples
