#!/usr/bin/env bash

function krb5logout {
  echo "* Destroying Kerberos 5 ticket..."
    kdestroy
}

# always log out when script is exited
trap krb5logout EXIT

# abort on error
set -ex

# check for correct number of arguments
if [ $# -ne 3 ]
then
    echo "wrong number of arguments"
    echo "usage: deploy_tag <ACTS_DIR> <DOC_DIR> <ACTS_MAIL>"
    exit 1
fi

# check for required environment variables
: ${CI_COMMIT_REF_NAME:?"'CI_COMMIT_REF_NAME' not set or empty"}

# check for Acts
ACTS_DIR=`readlink -f $1`
if [ ! -d "$ACTS_DIR" ]
then
    echo "ACTS_DIR='$ACTS_DIR' not found -> aborting"
    exit 1
fi

# check for doxygen documentation
DOC_DIR=`readlink -f $2`
if [ ! -d "$DOC_DIR" ]
then
    echo "DOC_DIR='$DOC_DIR' not found -> aborting"
    exit 1
fi

# get Acts version tag
VERSION=`basename $CI_COMMIT_REF_NAME`

# create tarball with source and copy it to server

# configure ssh to use kerberos
mkdir -p ~/.ssh/
echo "GSSAPIAuthentication yes
GSSAPITrustDNS yes
StrictHostKeyChecking no
GSSAPIDelegateCredentials yes" > ~/.ssh/config

ACTS_WWW_DIR="/eos/user/a/atsjenkins/www/ACTS"

ssh atsjenkins@lxplus.CERN.CH "mkdir -p $ACTS_WWW_DIR/$VERSION"

# copy doxygen documentation to server
scp -r $DOC_DIR atsjenkins@lxplus.cern.ch:$ACTS_WWW_DIR/$VERSION/doc

# send notification email
ssh atsjenkins@lxplus.CERN.CH "mail -v -s 'New tag Acts-$VERSION' -r 'atsjenkins@cern.ch' $3 <<EOF
Dear Acts enthusiasts,

a new tag '$VERSION' of the Acts project has been released. You can get the source code from git using

git clone https://gitlab.cern.ch/acts/acts-core.git acts
cd acts/
git checkout $VERSION

or you can download a tarball with the source from 

https://gitlab.cern.ch/acts/acts-core/repository/$VERSION/archive.tar.gz

Detailed documentation can be found at

https://acts.web.cern.ch/ACTS/$VERSION/doc/index.html

Cheers,
your friendly Acts robot
EOF"
