#!/usr/bin/env bash
set -e


if ! which python2 &> /dev/null; then
  echo "python2 not installed. Coverage reporting requires python2"
  exit 1
fi

PYTHON=$(which python2)

if [ ! -f CMakeCache.txt ]; then
    echo "Not in CMake build dir. Not executing"
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

set -x
mkdir -p coverage
$PYTHON $DIR/../cmake/gcovr -r $DIR/.. -e '../Tests/' -e '../Legacy/' --html --html-details -o coverage/index.html
$PYTHON $DIR/../cmake/gcovr -r $DIR/.. -e '../Tests/' -e '../Legacy/' --branches

