name: Detray

on:
  push:
    paths:
      - "Detray/**"
  pull_request:
    branches:
      - main
    paths:
      - "Detray/**"

# Cancel existing jobs on new pushes.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXSIZE: 500M
  CCACHE_KEY_SUFFIX: r2
  ACTS_SEQUENCER_FAIL_ON_UNMASKED_FPE: 0

# All the different build/test jobs.
jobs:

  # Native build jobs.
  native:

    # The different build modes to test.
    strategy:
      matrix:
        BUILD_TYPE: ["Debug"]
        PLATFORM:
          - OS: "ubuntu-latest"
            GENERATOR: "Unix Makefiles"
          - OS: "macos-latest"
            GENERATOR: "Ninja"

    # The system to run on.
    runs-on: ${{ matrix.PLATFORM.OS }}
    name: "native (${{ matrix.PLATFORM.OS }})"

    # The build/test steps to execute.
    steps:
    # Use a standard checkout of the code.
    - uses: actions/checkout@v6
    # Run the CMake configuration. Test that the metadata generation runs
    - name: Configure
      run: cmake --preset detray-full-fp64
                 -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }}
                 -DDETRAY_FAIL_ON_WARNINGS=ON
                 -DDETRAY_SET_LOGGING=DEBUG
                 -DDETRAY_SMATRIX_PLUGIN=OFF
                 -DDETRAY_FASTOR_PLUGIN=OFF
                 -DDETRAY_VC_AOS_PLUGIN=OFF
                 -DDETRAY_VC_SOA_PLUGIN=OFF
                 -DDETRAY_GENERATE_METADATA="default_metadata;itk_metadata;odd_metadata;toy_metadata;wire_chamber_metadata"
                 -S ${{ github.workspace }}/Detray -B build
                 -G "${{ matrix.PLATFORM.GENERATOR }}"
    # Perform the build.
    - name: Build
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }} -- -j 2

  # Containerised build jobs.
  host-container:

    # The different build modes to test.
    strategy:
      matrix:
        BUILD_TYPE: ["Release", "Debug"]
        SCALAR_TYPE: ["float", "double"]
        PLATFORM:
          - NAME: "HOST"
            CXX_STANDARD: "20"
            CONTAINER: "ghcr.io/acts-project/ubuntu2404:56"
            OPTIONS: -DDETRAY_EIGEN_PLUGIN=ON -DDETRAY_FASTOR_PLUGIN=OFF -DDETRAY_SMATRIX_PLUGIN=OFF -DDETRAY_VC_AOS_PLUGIN=OFF -DDETRAY_VC_SOA_PLUGIN=OFF

    # The system to run on.
    runs-on: ubuntu-latest
    container: ${{ matrix.PLATFORM.CONTAINER }}
    name: "host-container (${{ matrix.PLATFORM.NAME }}, C++${{ matrix.PLATFORM.CXX_STANDARD }})"

    # Use BASH as the shell from the image.
    defaults:
      run:
        shell: bash

    # Set the path to the test data files
    env:
      DETRAY_DATA_DIRECTORY: ${{ github.workspace }}/Detray/data/
      DETRAY_BFIELD_FILE: ${{ github.workspace }}/Detray/data/odd-bfield_v0_9_0.cvf

    # The build/test steps to execute.
    steps:
    # Use a standard checkout of the code.
    - uses: actions/checkout@v6
    # Get the data files for the tests
    - name: Download data files
      run: Detray/data/detray_data_get_files.sh
    # Run the CMake configuration.
    - name: Configure
      run: |
        source ${GITHUB_WORKSPACE}/Detray/CI/ci_setup.sh ${{ matrix.PLATFORM.NAME }}
        cmake --preset detray-full-fp32 \
          -DCMAKE_CXX_STANDARD=${{ matrix.PLATFORM.CXX_STANDARD }} \
          -DDETRAY_FAIL_ON_WARNINGS=ON \
          -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
          -DDETRAY_CUSTOM_SCALARTYPE=${{ matrix.SCALAR_TYPE }} \
          ${{ matrix.PLATFORM.OPTIONS }} \
          -S ${GITHUB_WORKSPACE}/Detray \
          -B build
    # Perform the build.
    - name: Build
      run: |
        source ${GITHUB_WORKSPACE}/Detray/CI/ci_setup.sh ${{ matrix.PLATFORM.NAME }}
        cmake --build build -- -j $(nproc)
    # Run the unit test(s).
    - name: Full Test
      if: "matrix.BUILD_TYPE == 'Release'"
      run: |
        cd build
        source ${GITHUB_WORKSPACE}/Detray/CI/ci_setup.sh ${{ matrix.PLATFORM.NAME }}
        ctest --output-on-failure
    - name: Unit Tests
      if: "matrix.BUILD_TYPE == 'Debug'"
      run: |
        cd build
        source ${GITHUB_WORKSPACE}/Detray/CI/ci_setup.sh ${{ matrix.PLATFORM.NAME }}
        ctest -R detray_unit_test_. -E "._eigen|._fastor|._vc_aos" --output-on-failure

  # Containerised build jobs.
  device-container:

    # The different build modes to test.
    strategy:
      matrix:
        BUILD_TYPE: ["Debug"]
        SCALAR_TYPE: ["float", "double"]
        PLATFORM:
          - NAME: "CUDA"
            CXX_STANDARD: "20"
            CONTAINER: "ghcr.io/acts-project/ubuntu2404_cuda:67"
            OPTIONS: -DDETRAY_BUILD_CUDA=ON -DDETRAY_SET_LOGGING=DEBUG -DDETRAY_EIGEN_PLUGIN=ON
          - NAME: "HIP-AMD"
            CXX_STANDARD: "20"
            CONTAINER: "ghcr.io/acts-project/ubuntu2404_rocm_oneapi:69"
            OPTIONS: -DCMAKE_PREFIX_PATH=/opt/rocm/lib/cmake/ -DCMAKE_HIP_PLATFORM=amd -DDETRAY_BUILD_HIP=ON -DDETRAY_SET_LOGGING=DEBUG -DDETRAY_EIGEN_PLUGIN=ON -DDETRAY_BUILD_BENCHMARKS=OFF -DDETRAY_BUILD_INTEGRATIONTESTS=OFF
          #- NAME: "HIP-NVIDIA"
          #  CXX_STANDARD: "20"
          #  CONTAINER:
          #  OPTIONS: -DCMAKE_HIP_PLATFORM=nvidia -DDETRAY_BUILD_HIP=ON -DDETRAY_SET_LOGGING=DEBUG -DDETRAY_EIGEN_PLUGIN=ON -DDETRAY_BUILD_BENCHMARKS=OFF
          - NAME: "SYCL"
            CXX_STANDARD: "20"
            CONTAINER: "ghcr.io/acts-project/ubuntu2404_oneapi:85"
            OPTIONS: -DDETRAY_BUILD_CUDA=OFF -DDETRAY_BUILD_SYCL=ON -DDETRAY_SET_LOGGING=DEBUG -DDETRAY_EIGEN_PLUGIN=ON

    # The system to run on.
    runs-on: ubuntu-latest
    container: ${{ matrix.PLATFORM.CONTAINER }}
    name: "device-container (${{ matrix.PLATFORM.NAME }}, C++${{ matrix.PLATFORM.CXX_STANDARD }})"

    # Use BASH as the shell from the image.
    defaults:
      run:
        shell: bash

    # The build/test steps to execute.
    steps:
    # Use a standard checkout of the code.
    - uses: actions/checkout@v6
    # Run the CMake configuration.
    - name: Configure
      run: |
        source ${GITHUB_WORKSPACE}/Detray/CI/ci_setup.sh ${{ matrix.PLATFORM.NAME }}
        cmake --preset detray-full-fp32 \
          -DCMAKE_CXX_STANDARD=${{ matrix.PLATFORM.CXX_STANDARD }} \
          -DCMAKE_CUDA_STANDARD=${{ matrix.PLATFORM.CXX_STANDARD }} \
          -DCMAKE_SYCL_STANDARD=${{ matrix.PLATFORM.CXX_STANDARD }} \
          -DCMAKE_HIP_STANDARD=${{ matrix.PLATFORM.CXX_STANDARD }} \
          -DDETRAY_BUILD_HOST=OFF \
          -DDETRAY_FASTOR_PLUGIN=OFF \
          -DDETRAY_SMATRIX_PLUGIN=OFF \
          -DDETRAY_VC_AOS_PLUGIN=OFF \
          -DDETRAY_VC_SOA_PLUGIN=OFF \
          -DDETRAY_FAIL_ON_WARNINGS=ON \
          -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
          -DDETRAY_CUSTOM_SCALARTYPE=${{ matrix.SCALAR_TYPE }} \
          ${{ matrix.PLATFORM.OPTIONS }} \
          -S ${GITHUB_WORKSPACE}/Detray \
          -B build
    # Perform the build.
    - name: Build
      run: |
        source ${GITHUB_WORKSPACE}/Detray/CI/ci_setup.sh ${{ matrix.PLATFORM.NAME }}
        cmake --build build
    - name: FP64 Compliance
      if: "matrix.PLATFORM.NAME == 'CUDA' && matrix.BUILD_TYPE == 'Debug' && matrix.SCALAR_TYPE == 'float'"
      continue-on-error: true
      run: ${GITHUB_WORKSPACE}/Detray/CI/find_f64_ptx.py --source ${GITHUB_WORKSPACE}/Detray --build build $(find build -name "*.ptx" ! -name "container_cuda_kernel.ptx")

  # Build and test the traccc plugin in ACTS
  traccc_plugin:

    runs-on: ubuntu-latest
    container: ghcr.io/acts-project/ubuntu2404:85
    env:
      INSTALL_DIR: ${{ github.workspace }}/install
      ACTS_LOG_FAILURE_THRESHOLD: WARNING

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Install dependencies
        uses: ./.github/actions/dependencies
        with:
          compiler: g++
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          env_file: .env

      - name: Restore ccache
        id: ccache-restore
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os  }}-${{ github.job }}-${{ env.CCACHE_KEY_SUFFIX }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os  }}-${{ github.job }}-${{ env.CCACHE_KEY_SUFFIX }}-

      - name: Configure
        run: >
          ccache -z &&
          CI/dependencies/run.sh .env
          cmake -B build -S .
          --preset=common
          -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}"
          -DCMAKE_BUILD_TYPE="Release"
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
          -DCMAKE_CXX_SCAN_FOR_MODULES=OFF
          -DCMAKE_FIND_FRAMEWORK="LAST"
          -DACTS_FORCE_ASSERTIONS=ON
          -DACTS_ENABLE_LOG_FAILURE_THRESHOLD=ON
          -DACTS_USE_SYSTEM_NLOHMANN_JSON=ON
          -DACTS_USE_SYSTEM_PYBIND11=ON
          -DACTS_BUILD_PLUGIN_DD4HEP=ON
          -DACTS_BUILD_PLUGIN_JSON=ON
          -DACTS_BUILD_EXAMPLES_PYTHON_BINDINGS=ON
          -DACTS_BUILD_PLUGIN_TRACCC=ON
          -DDETRAY_GENERATE_METADATA="odd_metadata;itk_metadata"
          -DTRACCC_SUPPORTED_DETECTORS="odd_detector;itk_detector"

      - name: Build
        run: cmake --build build

      - name: Build examples
        # these are excluded from the ALL target, but we want to test them here
        run: cmake --build build --target examples

      - name: ccache stats
        run: ccache -s

      - name: Save ccache
        uses: actions/cache/save@v5
        if: always()
        with:
          path: ${{ github.workspace }}/ccache
          key: ${{ steps.ccache-restore.outputs.cache-primary-key }}

      - name: Unit tests
        run: >
          CI/dependencies/run.sh .env
          ctest --test-dir build -j$(nproc)

      - name: Integration tests
        run: >
          CI/dependencies/run.sh .env
          cmake --build build --target integrationtests

      - name: Install
        run: cmake --build build --target install

      - name: Python sanity check after install
        shell: bash
        run: >
          source .env &&
          source install/python/setup.sh &&
          python -c "import acts; v = acts.Vector3(1,2,3)"
