# TRACCC library, part of the ACTS project (R&D line)
#
# (c) 2021-2026 CERN for the benefit of the ACTS project
#
# Mozilla Public License Version 2.0

name: Traccc

on:
  push:
    paths:
      - "Traccc/**"
      - "Detray/**"
      - ".github/workflows/traccc.yml"
  pull_request:
    branches:
      - main
    paths:
      - "Traccc/**"
      - "Detray/**"
      - ".github/workflows/traccc.yml"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  containers:
    name: ${{ matrix.platform.name }}-${{ matrix.build }}
    runs-on: ubuntu-latest
    container: ${{ matrix.platform.container }}
    permissions:
      contents: read
    strategy:
      matrix:
        platform:
          - name: CPU
            container: ghcr.io/acts-project/ubuntu2404:87
            options: --preset host-fp32
            run_tests: true
            enable_cuda: false
            enable_sycl: false
          - name: CPU
            container: ghcr.io/acts-project/ubuntu2404:87
            options: --preset host-fp64
            run_tests: false
            enable_cuda: false
            enable_sycl: false
          - name: CUDA
            container: ghcr.io/acts-project/ubuntu2404_cuda:87
            options: --preset cuda-fp32 -DTRACCC_BUILD_TESTING=FALSE
            run_tests: false
            enable_cuda: true
            enable_sycl: false
          - name: "SYCL Intel"
            container: ghcr.io/acts-project/ubuntu2404_oneapi:87
            options: --preset sycl-fp32
            run_tests: true
            enable_cuda: false
            enable_sycl: true
        build:
          - Release
          - Debug
        include:
          - platform:
              name: CUDA
              container: ghcr.io/acts-project/ubuntu2404_cuda:87
              options: --preset cuda-fp64
              run_tests: false
              enable_cuda: true
              enable_hip: false
              enable_sycl: false
            build: Release
          - platform:
              name: "ALPAKA_CPU"
              container: ghcr.io/acts-project/ubuntu2404:87
              options: --preset alpaka-fp32
              run_tests: true
              enable_cuda: false
              enable_hip: false
              enable_sycl: false
            build: Release
          - platform:
              name: "ALPAKA_CUDA"
              container: ghcr.io/acts-project/ubuntu2404_cuda:87
              options: --preset alpaka-fp32 -Dalpaka_ACC_GPU_CUDA_ENABLE=ON -DTRACCC_FAIL_ON_WARNINGS=OFF -DTRACCC_BUILD_CUDA_UTILS=ON
              run_tests: false
              enable_cuda: true
              enable_hip: false
              enable_sycl: false
            build: Release
          - platform:
              name: "ALPAKA_SYCL"
              container: ghcr.io/acts-project/ubuntu2404_oneapi:87
              options: --preset alpaka-fp32 -Dalpaka_ACC_CPU_B_SEQ_T_THREADS_ENABLE=OFF -Dalpaka_ACC_SYCL_ENABLE=ON -Dalpaka_SYCL_ONEAPI_GPU=ON -Dalpaka_SYCL_ONEAPI_GPU_DEVICES=spir64 -DTRACCC_BUILD_SYCL_UTILS=ON
              run_tests: false
              enable_cuda: false
              enable_hip: false
              enable_sycl: true
            build: Release
    # Use BASH as the shell from the images.
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: Install dependencies
        uses: ./.github/actions/dependencies
        with:
          compiler: g++
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          env_file: .env
      - name: Configure
        run: |
          source ${GITHUB_WORKSPACE}/.env
          source ${GITHUB_WORKSPACE}/Traccc/.github/ci_setup.sh ${{ matrix.platform.name }}
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.build }} \
            ${{ matrix.platform.options }} \
            -DTRACCC_SETUP_VECMEM=ON \
            -DTRACCC_SETUP_COVFIE=ON \
            -DTRACCC_SETUP_GOOGLETEST=ON \
            -DVECMEM_BUILD_CUDA_LIBRARY=${{ matrix.platform.enable_cuda && 'ON' || 'OFF' }} \
            -DVECMEM_BUILD_SYCL_LIBRARY=${{ matrix.platform.enable_sycl && 'ON' || 'OFF' }} \
            -DACTS_SETUP_VECMEM=OFF \
            -DACTS_SETUP_COVFIE=OFF \
            -DACTS_ENABLE_CUDA=${{ matrix.platform.enable_cuda && 'ON' || 'OFF' }} \
            -DDETRAY_SET_LOGGING=NONE \
            -DTRACCC_SUPPORTED_DETECTORS="default_detector;odd_detector;telescope_detector;toy_detector;itk_detector" \
            -DDETRAY_GENERATE_METADATA="itk_metadata" \
            -S ${GITHUB_WORKSPACE}/Traccc \
            -B build
      - name: Build
        run: |
          source ${GITHUB_WORKSPACE}/.env
          source ${GITHUB_WORKSPACE}/Traccc/.github/ci_setup.sh ${{ matrix.platform.name }}
          cmake --build build -- -j $(nproc)
      - name: Download data files
        if: "matrix.platform.run_tests"
        run: ${GITHUB_WORKSPACE}/Traccc/data/traccc_data_get_files.sh
      - name: Test
        if: "matrix.platform.run_tests && matrix.build == 'Release'"
        run: |
          source ${GITHUB_WORKSPACE}/.env
          cd build
          source ${GITHUB_WORKSPACE}/Traccc/.github/ci_setup.sh ${{ matrix.platform.name }}
          ctest --output-on-failure
      - name: FP64 Compliance
        if: "matrix.platform.name == 'CUDA' && matrix.build == 'Debug'"
        continue-on-error: true
        run: ${GITHUB_WORKSPACE}/Traccc/.github/find_f64_ptx.py --source ${GITHUB_WORKSPACE}/Traccc --build build $(find build -name "*.ptx")
